# <center><font color="#D38F00"><u>SORBONNE DATA ANALYTICS :<br/> Introduction à Python</u></font></center>

# <span style="color:#011C5D">2. Numpy</span>

La librairie **Numpy**, dont le nom est la contraction de *Numeric Python*, est l'une des librairies que vous serez le plus amenés à utiliser en Python pour le **calcul scientifique** et la **manipulation de données**.

Numpy offre des **performances** de calcul et de manipulation de données extrêmement intéressantes pour le langage Python, car il s'agit d'une librairie dont les dépendances ont été codées en **C**, puis **pré-compilées** pour les différentes plateformes sur lesquelles Numpy est distribué.

Malgré cette complexité, vous pouvez très facilement installer Numpy, via la commande `pip install numpy`, dont nous avons parlé plus tôt. Une fois installé, il vous suffit de l'importer au sein de votre script, généralement sous la convention `import numpy as np`.

In [ ]:
import numpy as np

Dans ce chapitre, vous aller apprendre à utiliser les fonctionnalités centrales de Numpy :

- Premièrement, nous étudierons une structure de données alternative aux listes : les **Numpy Arrays**
- En suite, nous apprendrons à utiliser de nombreuses **fonctions mathématiques** issues de la librairie Numpy
- Enfin, nous utiliserons le **Broadcasting** et la **vectorisation** afin d'effectuer des calculs multi-dimensionnels

![Numpy Logo](https://github.com/numpy/numpy/raw/main/branding/logo/primary/numpylogo.svg)

Je vous propose de rentrer tout de suite dans le vif du sujet, avec les arrays !

## <span style="color:#011C5D">2.1. Les Numpy Arrays</span>

### <span style="color:#011C5D">La déclaration</span>

Les **numpy arrays** sont l'une des fonctionnalités principales et centrales de Numpy. Il s'agit d'une alternative aux listes natives de Python.

Afin de créer un array Numpy, il vous suffit simplement de convertir une liste, via la fonction `np.array()`.

In [ ]:
a = np.array([1, 2, 3, 4])  # array créé à partir d'une liste
a

Attention, contrairement aux listes, tous les éléments d'un array sont d'un **même type** (souvent numérique, comme les integers, et les floats). Cela permet à la librairie Numpy d'appliquer des opérations à l'échelle d'un array de manière très **rapide** et **consistente**.

Si nécessaire, vous pouvez **préciser** ce type au moment de la création de l'array. Dans l'exemple ci-dessous, nous voulons que les nombres soient stockés sous le type float, et non sous le type integer.

In [ ]:
a = np.array([1, 2, 3, 4], float)  # On peut préciser le type des éléments
a

Comme pour les listes natives, vous accédez aux éléments au sein d'un array via l'**accesseur** représenté par des crochet `[]`.

In [ ]:
a[2]

Le **slicing** fonctionne de la même manière que pour les listes : séparez votre index de début et votre index de fin par le symbole `:`.

*L'index de fin est ici aussi exclus.*

In [ ]:
a[1:3]

Si vous appiquez la fonction `type()` sur un array, vous vous apercevrez que le véritable nom des arrays est `numpy.ndarray` pour "*n-dimensionnal array*": "*tableau de dimension n*".

In [ ]:
type(a)  # le type du tableau est np.ndarray

C'est le cas parceque les **arrays Numpy** ont été conçus dans le but de stocker des données **multi-dimensionnelles**.

Pour ce faire, il vous suffit de **convertir des listes imbriquées** en array. Ici, nous créons un array de 2 dimensions : 3 lignes, et 4 colonnes.

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # array de 2 dimensions (3 lignes, 4 colonnes)
a

Vous pouvez créer des arrays Numpy jusqu'à **32 dimensions** !

### <span style="color:#011C5D">L'accession</span>

Pour **sélectionner un élément** d'un array multi-dimensionnel, vous devrez préciser l'index souhaité dans chacune des dimensions, et séparer ces dimensions par une virgule.

Ici, nous sélectionnons l'élément de la ligne 1, et de la colonne 2.

In [ ]:
a[1, 2]  # élément de la ligne 1, colonne 2

Le **slicing** des arrays Numpy fonctionne de la même manière que pour les listes Python natives, mais est **généralisé** aux multiples dimensions.

Ainsi, vous séparerez les différentes dimensions aux sein des slices par une virgule `,`, et pourrez sélectionner tous les éléments d'une dimensions via le symbole `:`.

Dans l'exemple ci-dessous, nous sélectionnons toutes les lignes de `a`, mais uniquement la colonne 1.

In [ ]:
a[:, 1]  # toutes les lignes, colonne 1

Vous pouvez aussi **modifier** un array via le **slicing**.

Ici, nous sélectionnons l'intersection des deux premières lignes, et des colonnes 1 et 2, et lui appliquons la valeur "0".

In [ ]:
a[:2, 1:3] = 0
a

### <span style="color:#011C5D">Les méthodes et attributs  utiles</span>

Une fois que vous avez créé un Numpy array, vous pouvez obtenir des informations sur celui-ci via ses attributs.

Par exemple, vous pouvez **accéder au type des éléments** au sein du tableau via l'attribut `.dtype` d'un array.

In [ ]:
a.dtype  # la propriété .dtype contient le type des éléments du tableau

L'attribut `.shape` est aussi très utiles, puisqu'il renvoie la longueur de chaque dimension d'un array.

In [ ]:
a.shape  # la propriété .shape contient un tuple donnant la taille de chaque dimension

Notez que `.shape` et `.dtype` ne sont pas des méthodes, mais des **attributs**: vous ne devez pas utiliser de paranthèses après leur nom, et ne pouvez pas passer d'arguments. Ils sont simplement des **informations** sur l'objet que vous utilisez, en l'occurence le Numpy array `a`.

Pour **modifier la forme** d'un array, vous utiliserez généralement deux méthodes :

- La méthode `.reshape`, qui change la forme d'un array par celle que vous lui donnez. Dans notre cas, nous passons d'un array de dimensions "*3 lignes*", "*4 colonnes*" à un array de dimensions "*6 lignes*", "*2 colonnes*".

In [ ]:
a.reshape(6,2)  # change la forme de la matrice de (3, 4) à (6, 2)

La seconde méthode est la méthode `.flatten()` qui vous permettra tout simplement de rendre l'array uni-dimensionnel.

In [ ]:
a.flatten()  # rend l'array uni-dimensionnel

Si vous souhaitez **inverser les axes** d'un array, la fonction `.transpose()` est similaire à celle d'Excel: pour le cas "*2 dimensions*", les lignes deviennent les colonnes et vice-versa.

In [ ]:
a.transpose()  # inverse les axes

La dernière méthode d'array que nous allons voir est la méthode `.fill`. Elle vous permettra d'**appliquer une valeur** à l'ensemble d'un array: on dit qu'elle "remplit" l'array.

In [ ]:
a.fill(0)  # Remplit l'array d'une valeur
a

### <span style="color:#011C5D">La création d'arrays</span>

Nous allons maintenant découvrir quelques fonctions utiles pour **générer des données** avec Numpy.

Pour commencer, la fonction `np.arange()` est très similaire à la fonction `range()` native de Python : elle permet de **générer** un array de valeurs **entre deux nombres**.

Ici, nous générons un array contenant les nombres de 2 à 20 (exclus), avec un pas de 2.

In [ ]:
np.arange(2, 20, 2)

Ensuite, la fonction `np.full()` permet de générer un array d'une forme donnée, et de le **remplir** d'une valeur donnée.

Dans notre exemple, nous générons un array de dimensions "*10 lignes*", "*2 colonnes*", remplies de la valeur *5*.

In [ ]:
np.full((10, 2), 5)

Enfin, avec la fonction `np.random.rand()`, vous pourrez générer un array remplis de nombres aléatoires entre 0 et 1, dans une distribution uniforme.

In [ ]:
np.random.rand(10, 2)

### <span style="color:#011C5D">La manipulation d'arrays</span>

Avant de passer aux exercices, nous allons découvrir comment combiner plusieurs arrays. Pour commencer, nous allons instancier deux variables, `a` et `b` qui contiendrons chacune un Numpy array de dimensions identiques.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

In [ ]:
b = np.array([[7, 8, 9], [10, 11, 12]])
b

Vous serez fréquemment amenés à vouloir **fusionner deux arrays** en un seul.

Pour ce faire, vous utiliserez la fonction `np.concatenate()` qui prendra deux arguments : une liste des arrays à concaténer, et l'axe sur lequel effectuer la concaténation.

Dans notre exemple, `a` et `b` sont chacun bi-dimensionnels, ce qui veut dire qu' ils possèdent deux axes (lignes, et colonnes). L'axe 0 représente les lignes, et l'axe 1 représente les colonnes.

Ainsi, concaténer sur l'axe 0 va "ajouter des lignes", c'est à dire placer b "sous" a.

In [ ]:
np.concatenate((a, b), axis=0)  # Concatenation sur le premier axe

Et concaténer sur l'axe 1 va "ajouter des colonnes", c'est à dire placer b "à droite de" a.

In [ ]:
np.concatenate((a, b), axis=1)  # Concatenation sur le deuxième axe

### <span style="color:#011C5D">Exercices sur les Numpy Arrays</span>

#### <span style="color:#011C5D">Exercice 1</span>

Créez un array Numpy contenant les **nombres entiers de 0 à 20** (inclus) sous le type **float** de Numpy. Inverser le tableau (le dernier nombre devient le premier, ..., le premier nombre devient le dernier), puis affichez le.

In [ ]:
##### Rentrez votre code ici ######


In [ ]:
##### Corrigé #####
%load exercices/2_1_arrays_1.py

#### <span style="color:#011C5D">Exercice 2</span>

Créez puis affichez un array Numpy de dimensions 5x5, composé de 1 sur les bords et de 0 au centre.

In [ ]:
##### Rentrez votre code ici ######


In [ ]:
##### Corrigé #####
%load exercices/2_1_arrays_2.py

In [ ]:
# Resultat attendu :
# [[1 1 1 1 1]
#  [1 0 0 0 1]
#  [1 0 0 0 1]
#  [1 0 0 0 1]
#  [1 1 1 1 1]]

## <span style="color:#D38F00">Félicitations !</span>

Dans ce cours, vous avez découvert une **structure de données** que vous utiliserez fréquemment à l'avenir : les **Numpy arrays**.

Vous êtes désormais capables de **créer** et **manipuler** ces structures, et nous allons bientôt découvrir comment les utiliser dans leur plein potentiel !